### PR TITLE
Move to Bumblebee 1.2

### PR DESCRIPTION
**Pull request by PioterB**
Implement missing ITextField<T>.Press<T>() method.

### CODE REVIEW

**Comment by PioterB** [comment]
As a result i expect new nuget package :)

**Comment by PioterB** [comment]
one more think, i forgot to raise dependency from Bumbleebee 1.0.7 to 1.2 i nuspec file

**Comment by toddmeinershagen** [comment]
@PioterB You can update the nuspec file and check it in to your repository.  Then it will appear in this pull request.  Let me know when complete, and I will merge it all in and make a release.

**Comment by PioterB** [comment]
done

**Comment by toddmeinershagen** [comment]
Thanks for making the updates - really appreciate it.  I will try to get this published to NuGet by this evening.

**Pull request merged**
